version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - /home/docker/stack1/homebridge/config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581

  portainer:
    image: portainer/portainer-ce:linux-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/stack1/portainer/data:/data
    environment:
      - TZ=MST7MDT
    ports:
      - 9000:9000
    restart: always
